#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import plistlib
import shutil
import sqlite3
import stat
from pathlib import Path


TEXT_SUFFIXES = {".py", ".js", ".md", ".txt", ".json", ".sh", ".command", ".html"}
OLD_A_ROOT = "/Users/messi/Documents/Codex/2026-06-26/re"
OLD_LIEPIN_ROOT = "/Users/messi/Documents/Codex/2026-06-18/liepin-intelligence"
OLD_SKILL_ROOT = "/Users/messi/.codex/skills/a-system-workbench"
OLD_HOME = "/Users/messi"


def copy_tree(source: Path, target: Path) -> None:
    shutil.copytree(
        source,
        target,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by A 系统 portable installer. No secrets are stored here."]
    lines.extend(f"export {key}={shell_quote(value)}" for key, value in values.items())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def rewrite_paths(root: Path, replacements: dict[str, str]) -> list[str]:
    changed: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        updated = text
        for old, new in replacements.items():
            updated = updated.replace(old, new)
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            changed.append(str(path.relative_to(root)))
    return changed


def initialize_db(schema: Path, target: Path) -> str:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        return "existing"
    conn = sqlite3.connect(target)
    try:
        conn.executescript(schema.read_text(encoding="utf-8"))
        result = conn.execute("PRAGMA integrity_check").fetchone()[0]
        if result != "ok":
            raise RuntimeError(f"empty DB integrity check failed: {result}")
    finally:
        conn.close()
    return "empty_schema"


def write_launch_agent(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        plistlib.dump(payload, handle, sort_keys=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bundle-root", type=Path, required=True)
    parser.add_argument("--install-root", type=Path, required=True)
    parser.add_argument("--python-bin", required=True)
    parser.add_argument("--arch", choices=["arm64", "x86_64"], required=True)
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--cdp-port", type=int, default=9223)
    parser.add_argument("--no-launchagent", action="store_true")
    parser.add_argument("--no-cdp", action="store_true")
    parser.add_argument("--skip-skill", action="store_true")
    parser.add_argument("--codex-home", type=Path, default=Path.home() / ".codex")
    args = parser.parse_args()

    bundle = args.bundle_root.resolve()
    install = args.install_root.expanduser().resolve()
    payload = bundle / "payload"
    app_root = install / "app"
    liepin_root = install / "integrations" / "liepin-intelligence"
    outputs = app_root / "outputs"
    db = outputs / "talent_system_v3.db"
    html = outputs / "A系统.html"

    for directory in (install / "bin", install / "config", install / "logs", app_root / "inputs", outputs, liepin_root / "outputs", install / "extensions"):
        directory.mkdir(parents=True, exist_ok=True)

    copy_tree(payload / "app", app_root)
    copy_tree(payload / "integrations" / "liepin-intelligence", liepin_root)
    for extension in ("liepin-reply-assistant-extension", "xsaas-candidate-assistant-extension"):
        integrated_extension = liepin_root / extension
        copy_tree(payload / "extensions" / extension, integrated_extension)
        public_extension = install / "extensions" / extension
        if public_extension.exists() or public_extension.is_symlink():
            if public_extension.is_dir() and not public_extension.is_symlink():
                shutil.rmtree(public_extension)
            else:
                public_extension.unlink()
        public_extension.symlink_to(integrated_extension)
    copy_tree(payload / "codex-skill" / "scripts", app_root / "tools")
    copy_tree(bundle / "bin", install / "bin")
    shutil.copy2(bundle / "requirements.txt", install / "requirements.txt")
    shutil.copy2(bundle / "README.md", install / "README.md")
    shutil.copy2(payload / "AGENTS.md", install / "AGENTS.md")

    data_source = payload / "data" / "talent_system_v3.db"
    if data_source.exists() and not db.exists():
        shutil.copy2(data_source, db)
        db_mode = "authorized_snapshot"
    else:
        db_mode = initialize_db(payload / "data" / "schema.sql", db)

    legacy_db = outputs / "talent_system_v3_20260629.db"
    if legacy_db.exists() or legacy_db.is_symlink():
        legacy_db.unlink()
    legacy_db.symlink_to(db.name)

    env_values = {
        "A_SYSTEM_HOME": str(install),
        "A_SYSTEM_ROOT": str(app_root),
        "A_SYSTEM_DB": str(db),
        "A_SYSTEM_HTML": str(html),
        "A_SYSTEM_LIEPIN_ROOT": str(liepin_root),
        "A_SYSTEM_LIEPIN_OUTPUTS": str(liepin_root / "outputs"),
        "A_SYSTEM_PORT": str(args.port),
        "A_SYSTEM_CDP_PORT": str(args.cdp_port),
        "A_SYSTEM_ARCH": args.arch,
        "A_SYSTEM_PYTHON": str(Path(args.python_bin).resolve()),
        "A_SYSTEM_AGENT_BASE_URL": "https://max.jojocode.com/v1",
        "A_SYSTEM_AGENT_MODEL": "gpt-5.5",
        "A_SYSTEM_AGENT_KEYCHAIN_SERVICE": "cognee-codex-llm",
        "A_SYSTEM_AGENT_KEYCHAIN_ACCOUNT": "max.jojocode.com",
        "A_SYSTEM_AGENT_MAX_WORKERS": "1",
    }
    write_env(install / "config" / "a-system.env", env_values)

    skill_root = args.codex_home.expanduser() / "skills" / "a-system-workbench"
    replacements = {
        OLD_A_ROOT: str(app_root),
        OLD_LIEPIN_ROOT: str(liepin_root),
        OLD_SKILL_ROOT: str(skill_root),
        "/Users/messi/Documents/Codex/2026-06-26/xia/outputs/positions.xlsx": str(app_root / "inputs" / "positions.xlsx"),
        "/Users/messi/Documents/Codex/2026-06-26/li/outputs/人才流程情况表_从触达到入职闭环.xlsx": str(app_root / "inputs" / "candidate_flow.xlsx"),
        "/Users/messi/Documents/Codex/2026-06-25/ni/outputs/岗位池厚度本地只读快照_20260629.md": str(app_root / "inputs" / "position_thickness.md"),
        "/Users/messi/Documents/Codex/2026-06-25/ni/outputs/岗位池厚度本地只读快照_20260629.json": str(app_root / "inputs" / "position_thickness.json"),
        "/Users/messi/.hermes/talent_pool.db": str(app_root / "inputs" / "talent_pool.db"),
        'Path.home() / "Documents" / "Codex" / "2026-06-18" / "liepin-intelligence"': f'Path("{liepin_root}")',
        '"$HOME/A-System': f'"{install}',
    }
    changed = rewrite_paths(install, replacements)

    if not args.skip_skill:
        if skill_root.exists():
            shutil.rmtree(skill_root)
        copy_tree(payload / "codex-skill", skill_root)
        rewrite_paths(skill_root, replacements)

    launch_agents: list[str] = []
    if not args.no_launchagent:
        service_plist = Path.home() / "Library" / "LaunchAgents" / "ai.a-system.workbench.plist"
        write_launch_agent(
            service_plist,
            {
                "Label": "ai.a-system.workbench",
                "ProgramArguments": [str(Path(args.python_bin).resolve()), str(liepin_root / "scripts" / "liepin_workbench_server.py"), "--host", "127.0.0.1", "--port", str(args.port), "--no-open-refresh"],
                "WorkingDirectory": str(liepin_root / "scripts"),
                "EnvironmentVariables": env_values,
                "RunAtLoad": True,
                "KeepAlive": True,
                "StandardOutPath": str(install / "logs" / "workbench.log"),
                "StandardErrorPath": str(install / "logs" / "workbench-error.log"),
            },
        )
        launch_agents.append(str(service_plist))

    if not args.no_cdp:
        cdp_plist = Path.home() / "Library" / "LaunchAgents" / "ai.a-system.chrome-cdp.plist"
        write_launch_agent(
            cdp_plist,
            {
                "Label": "ai.a-system.chrome-cdp",
                "ProgramArguments": [
                    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                    f"--remote-debugging-port={args.cdp_port}",
                    f"--user-data-dir={install / 'chrome-profile'}",
                    "--no-first-run",
                    "--no-default-browser-check",
                    "https://h.liepin.com/",
                ],
                "RunAtLoad": False,
                "KeepAlive": {"SuccessfulExit": False, "Crashed": True},
            },
        )
        launch_agents.append(str(cdp_plist))

    for script in (install / "bin").glob("*"):
        if script.is_file():
            script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    metadata = {
        "ok": True,
        "install_root": str(install),
        "architecture": args.arch,
        "python": str(Path(args.python_bin).resolve()),
        "db_mode": db_mode,
        "db": str(db),
        "html": str(html),
        "skill": None if args.skip_skill else str(skill_root),
        "launch_agents": launch_agents,
        "rewritten_files": len(changed),
    }
    (install / "install-metadata.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(metadata, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
